name: "compare-package-json-version-with-latest"
description: "Allows us to compare your local `package.json` version with a Github Package Registry's latest version."

runs:
  using: "node16"
  main: "dist/index.js"

inputs:
  repository:
    description: "The repository to get the latest package from.  Defaults to `env.GITHUB_REPOSITORY`."
    required: false
  directory:
    description: "Directory where your `package.json` can be found.  Defaults to `env.GITHUB_WORKSPACE`."
    required: false

outputs:
  matches:
    description: "If the versions match, one of 'true' | 'false'"
  newer:
    description: "If the current version is newer, one of 'true' | 'false'"
  diff:
    description: "The diff between versions, one of null | 'major' | 'premajor' | 'minor' | 'preminor' | 'patch' | 'prepatch' | 'prerelease'"
  current_version:
    description: "The current version in package.json"
  latest_version:
    description: "The latest, remote version"
