on: push

name: Jest Suite

jobs:
  jest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 16 # This version is up to date with react master as of Sept 20, 2022.

      - run: yarn install --ignore-optional --frozen-lockfile --non-interactive --check-files

      - run: yarn build

      - run: yarn jest:ci
